
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://jingyzhu.github.io"
# url: "http://www-personal.umich.edu/~jingyz"
# url: "http://web.eecs.umich.edu/~jingyz"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

baseurl: /
# baseurl: /~jingyz

# Google tracking id

google-tracking-id: "UA-151744066-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Jingyuan Zhu"
title: "Jingyuan Zhu"
description: "Personal Website about Jingyuan Zhu"
keywords: "Jingyuan, Zhu"
favicon: "/img/favicon.ico"

################
# Header layout #
################

# black-favicon: "/img/favicon2.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 50
start-delay: 200
delete-delay: 3000
lines: # You can add HTML Tags in the Text
  - text: "Hello!"
  - text: "My name is Jingyuan"
  - text: "I'm a first year Ph.D in CS @ UMich"
  # - text: "你好"
  # - text: ""
  # - text: "こんにちは"
  # - text: "Bonjour"
  # - text: "Hola"

me-img: "/img/self.jpg"

# To use facebook profile pic comment the previous line and uncomment the following
# line, and replace 'user_id' with your facebook user id.
# Facebook user id can be found by clicking on your profile pic and the large number
# in the end of the url just before '&type' is your user id.
# Note: fbid is not the same as user id and user id only contains numbers

# me-img: "https://graph.facebook.com/user_id/picture?type=large&width=500&height=500"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: False
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "Jingyuan Zhu"

syntax-highlight: True

############
# Eduction #
############

events:
  - image: "/img/education/umich.png"
    date: "September 2019 - Today"
    description: "PhD Candidate @ CSE University of Michigan"
  - image: "/img/education/umich.png"
    date: "September 2017 - April 2019"
    description: "B.S.E in CS <br> @ University of Michigan"
  - image: "/img/education/ji.jfif"
    date: "September 2015 - August 2019"
    description: "B.S.E in ECE <br> @ Shanghai Jiao Tong University"

# First image of the Education

# timeline-img: "/img/timeline/default.png"


###########
# Contact #
###########

# email: "jingyz@umich.edu"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
# author_blurb: ""
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/"
  # - title: "envelope"
  #   url: "mailto:jingyz@umich.edu"
  - title: "github"
    url: "https://github.com/JingyZhu/"
  - title: "linkedin"
    url: "https://www.linkedin.com/in/%E6%99%AF%E5%85%83-%E6%9C%B1-00368b156/?locale=en_US"
  - title: "steam-square"
    url: "https://steamcommunity.com/profiles/76561198239444060/"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Education: 'education'
  Project: 'project'
  Publication: 'publication'
  Blog: 'latest-post'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

markdown: kramdown

plugins:
  - jekyll-paginate
  - jemoji


